#!/usr/bin/env python3
"""Generate the two matched scene pools for the weather-exposure ablation.

Both pools are derived from the pool the KNN backbone (model E, model_2999) was
trained on:

    configs/scene_factory/generated/scene_factory_256scene_random_0414_train_friction.yaml

and differ from each other in EXACTLY ONE field: ``water_film_mm``.

  alldry    every world at 0.0 mm  -> the policy never encounters wet ground
  wet0to08  water film spread evenly over [0.0, 0.8] mm across the 256 worlds

Everything else -- scene_json assignment, world order, grid layout, and the
per-scene ``road_type`` -- is copied through verbatim, so the two pools are
matched on surface type and geometry and the only free variable is water depth.

Why 0.8 mm is the ceiling: the TRFC Y_R defect collapses mu to exactly 0 for
h >= 0.85 mm (see tasks/fix_trfc_yr_hydroplaning_cliff.md).  The backbone's own
training pool put 73/256 worlds (28.5%) above that line, i.e. on frictionless
ice.  Staying at or below 0.8 mm keeps every world in the regime where the
friction model still produces a physically meaningful mu.

Water film is assigned to scenes via a deterministic shuffle (seed 42) rather
than in scene order, so depth is not correlated with scene index.

  KNOWN LIMITATION: the scene <-> water-film pairing is still FIXED for the whole
  run.  Because the policy gets a privileged map, it can in principle infer a
  world's friction from its geometry and never consult the weather token.  Fixing
  that properly requires per-episode friction resampling; it is not addressed
  here, and it applies equally to both pools and to the original E pool.

Usage:
    python scripts/make_weather_ablation_pools.py
"""
from __future__ import annotations

import random
from pathlib import Path

import yaml

BASE = Path(
    "configs/scene_factory/generated/scene_factory_256scene_random_0414_train_friction.yaml"
)
OUT_DIR = Path("configs/scene_factory/generated")
MAX_FILM_MM = 12.0
SHUFFLE_SEED = 42

# The base pool pairs 0.3 mm with 2.0 mm/h; reuse that ratio so precip_intensity
# stays self-consistent.  It does NOT affect mu -- friction_api.py only falls back
# to intensity when water_film_mm is absent (friction_api.py:305) -- but
# trfc/curriculum_report.py reports it.
MMPH_PER_MM = 2.0 / 0.3


def _header(title: str, detail: str) -> str:
    return (
        f"# {title}\n"
        f"# Generated by scripts/make_weather_ablation_pools.py -- do not hand-edit.\n"
        f"# Derived from {BASE.name}.\n"
        f"#\n"
        f"# {detail}\n"
        f"#\n"
        f"# Matched to its sibling pool on scene assignment, world order, and\n"
        f"# per-scene road_type.  water_film_mm is the ONLY field that differs.\n"
        f"# Water film spans 0-{MAX_FILM_MM} mm.  The old 0.8 mm ceiling existed only to\n"
        f"# dodge the TRFC Eq.(12) mu=0 cliff; that was a dimensional bug and is FIXED\n"
        f"# (tasks/fix_trfc_yr_hydroplaning_cliff.md), so the wide span is now valid and\n"
        f"# is required to reach the regime where friction actually binds.\n"
    )


def _set_weather(assignment: dict, film_mm: float) -> None:
    """Overwrite only the water/precip fields, preserving road_type."""
    friction = assignment.setdefault("friction", {})
    film_mm = round(float(film_mm), 4)
    friction["water_film_mm"] = film_mm
    if film_mm <= 0.0:
        friction["precip_type"] = "clear"
        friction["precip_intensity_mmph"] = 0.0
    else:
        friction["precip_type"] = "rain"
        friction["precip_intensity_mmph"] = round(film_mm * MMPH_PER_MM, 3)


def build(films: list[float]) -> dict:
    pool = yaml.safe_load(BASE.read_text())
    assignments = pool["world"]["assignments"]
    if len(films) != len(assignments):
        raise SystemExit(f"film count {len(films)} != assignment count {len(assignments)}")
    for assignment, film in zip(assignments, films):
        _set_weather(assignment, film)
    return pool


def write(pool: dict, path: Path, header: str) -> None:
    body = yaml.safe_dump(pool, sort_keys=False, default_flow_style=False)
    path.write_text(header + body)
    films = [a["friction"]["water_film_mm"] for a in pool["world"]["assignments"]]
    roads: dict[str, int] = {}
    for a in pool["world"]["assignments"]:
        roads[a["friction"]["road_type"]] = roads.get(a["friction"]["road_type"], 0) + 1
    print(f"[write] {path}")
    print(f"        worlds {len(films)}  film min {min(films):.4f} max {max(films):.4f} "
          f"mean {sum(films)/len(films):.4f}")
    print(f"        road_type {roads}")


def main() -> None:
    n = len(yaml.safe_load(BASE.read_text())["world"]["assignments"])

    # ---- arm A: all dry ---------------------------------------------------
    write(
        build([0.0] * n),
        OUT_DIR / "scene_factory_256scene_0414_alldry.yaml",
        _header(
            "Weather-exposure ablation, arm A: ALL DRY.",
            "Every world at water_film_mm = 0.0.  The policy trained on this pool has\n"
            "# no exposure to wet ground at all -- it does not know the condition exists.",
        ),
    )

    # ---- arm B: even spread over [0, 0.8] mm ------------------------------
    films = [MAX_FILM_MM * i / (n - 1) for i in range(n)]
    random.Random(SHUFFLE_SEED).shuffle(films)
    write(
        build(films),
        OUT_DIR / "scene_factory_256scene_0414_wet0to12.yaml",
        _header(
            f"Weather-exposure ablation, arm B: EVEN 0.0-{MAX_FILM_MM} mm.",
            f"water_film_mm spread evenly over [0.0, {MAX_FILM_MM}] mm across the {n} worlds,\n"
            f"# then shuffled with seed {SHUFFLE_SEED} so depth is uncorrelated with scene index.\n"
            "# Built on the CORRECTED TRFC model.  Every world has a usable, non-zero mu,\n"
            "# and the span now reaches the region where friction binds on this vehicle.",
        ),
    )


if __name__ == "__main__":
    main()
